go2w/parkour:
  model_name: "base_jit.pt"
  num_observations: 59
  observations: ["ang_vel", "gravity_vec","yaw_angle", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: [9,8,7,6,5,4,3,2,1,0]  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0]
  rl_kp: [50.0, 50.0, 50.0,0.0,
          50.0, 50.0, 50.0,0.0,
          50.0, 50.0, 50.0,0.0,
          50.0, 50.0, 50.0,0.0]
  rl_kd: [1.0, 1.0, 1.0,0.5,
          1.0, 1.0, 1.0,0.5,
          1.0, 1.0, 1.0,0.5,
          1.0, 1.0, 1.0,0.5]
  fixed_kp: [70.0, 70.0, 70.0, 0.0,
             70.0, 70.0, 70.0, 0.0,
             70.0, 70.0, 70.0, 0.0,
             70.0, 70.0, 70.0, 0.0]
  fixed_kd: [5.0, 5.0, 5.0, 0.5,
             5.0, 5.0, 5.0, 0.5,
             5.0, 5.0, 5.0, 0.5,
             5.0, 5.0, 5.0, 0.5]
  num_of_dofs: 16
  action_scale: [0.25, 0.25, 0.25, 10.0,
                 0.25, 0.25, 0.25, 10.0,
                 0.25, 0.25, 0.25, 10.0,
                 0.25, 0.25, 0.25, 10.0]

  wheel_indices: [3, 7, 11, 15]
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5, 23.5]
  default_dof_pos: [ 0.00, 0.67, -1.30,0.00,
                     0.00, 0.67, -1.30,0.00,
                     0.00, 0.67, -1.30,0.00,
                     0.00, 0.67, -1.30,0.00]
                    
  joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
