controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    robot_joint_controller:
      type: joint_trajectory_controller/JointTrajectoryController

robot_joint_controller:
  ros__parameters:
    joints:
      - FR_hip_joint
      - FL_hip_joint
      - RR_hip_joint
      - RL_hip_joint
      - FR_thigh_joint
      - FL_thigh_joint
      - RR_thigh_joint
      - RL_thigh_joint
      - FR_calf_joint
      - FL_calf_joint
      - RR_calf_joint
      - RL_calf_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_stopping_all_trajectories: true
    allow_integration_in_goal_trajectories: true
    open_loop_control: true
    allow_stalling: false

    gains:
      FR_hip_joint:
        p: 100.0
        d: 1.0
      FL_hip_joint:
        p: 100.0
        d: 1.0
      RR_hip_joint:
        p: 100.0
        d: 1.0
      RL_hip_joint:
        p: 100.0
        d: 1.0
      FR_thigh_joint:
        p: 100.0
        d: 1.0
      FL_thigh_joint:
        p: 100.0
        d: 1.0
      RR_thigh_joint:
        p: 100.0
        d: 1.0
      RL_thigh_joint:
        p: 100.0
        d: 1.0
      FR_calf_joint:
        p: 100.0
        d: 1.0
      FL_calf_joint:
        p: 100.0
        d: 1.0
      RR_calf_joint:
        p: 100.0
        d: 1.0
      RL_calf_joint:
        p: 100.0
        d: 1.0 